---
language: node_js
node_js:
  - "4.2"

sudo: false

cache:
  directories:
    - node_modules

python:
  - "2.7"

before_install:
  - python --version
  - npm config set spin false
  - npm install -g node-gyp
  - npm install -g bower
  - npm install phantomjs-prebuilt

install:
  - npm install
  - bower install

script:
  - npm test
